# .github/workflows/cron-hello.yml
name: Hello Cron Job

on:
  schedule:
    - cron: '57 14 * * *'  # Runs every day at 9:00 AM UTC
permissions: raed-all
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello"
