# .github/workflows/cron-hello.yml
name: Hello Cron Job 58

on:
  workflow_dispatch: 
  schedule:
    - cron: '04 15 * * *'  # Runs every day at 9:00 AM UTC
permissions: read-all
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello"
